name: sustainability_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - async-timeout=4.0.3
  - attrs=24.2.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - bleach=6.1.0
  - bokeh=3.1.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - catalogue=2.0.10
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpathlib=0.20.0
  - colorama=0.4.6
  - confection=0.1.4
  - contourpy=1.1.1
  - cycler=0.12.1
  - cymem=2.0.8
  - cython-blis=0.7.10
  - datasets=3.0.2
  - dill=0.3.8
  - filelock=3.16.1
  - fonttools=4.53.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.9.0
  - future=1.0.0
  - gflags=2.2.2
  - glog=0.7.1
  - h2=4.1.0
  - hdbscan=0.8.38.post1
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - jinja2=3.1.4
  - joblib=1.4.2
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - langcodes=3.3.0
  - langdetect=1.0.9
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.12.1
  - libcxx=19.1.7
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.35.0
  - libgoogle-cloud-storage=2.35.0
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnghttp2=1.64.0
  - libopenblas=0.3.25
  - libparquet=17.0.0
  - libpng=1.6.47
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.6
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - llvm-openmp=19.1.7
  - llvmlite=0.41.1
  - lz4-c=1.10.0
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - multidict=6.0.5
  - multiprocess=0.70.16
  - munkres=1.1.4
  - murmurhash=1.0.10
  - ncurses=6.5
  - ninja=1.12.1
  - nltk=3.9.1
  - numba=0.58.1
  - numpy=1.24.4
  - openjpeg=2.5.3
  - openssl=3.4.1
  - orc=2.0.3
  - packaging=24.2
  - pandas=2.0.3
  - panel=1.2.3
  - param=1.13.0
  - patsy=0.5.6
  - pillow=10.4.0
  - pip=24.3.1
  - platformdirs=4.3.6
  - plotly=5.24.1
  - pooch=1.8.2
  - preshed=3.0.9
  - pthread-stubs=0.4
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.18.0
  - pynndescent=0.5.13
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.8
  - pytz=2024.2
  - pyviz_comms=3.0.3
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.7.24
  - requests=2.32.3
  - rich=13.9.4
  - safetensors=0.4.4
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.3.0
  - shellingham=1.5.4
  - six=1.16.0
  - smart-open=7.0.5
  - smart_open=7.0.5
  - snappy=1.2.1
  - spacy=3.7.6
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.4.8
  - statsmodels=0.14.1
  - tbb=2022.0.0
  - tenacity=9.0.0
  - textblob=0.15.3
  - thinc=8.2.5
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tokenizers=0.20.1
  - tornado=6.4.1
  - tqdm=4.67.1
  - transformers=4.46.3
  - typer=0.12.5
  - typer-slim=0.12.5
  - typer-slim-standard=0.12.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - uc-micro-py=1.0.3
  - umap-learn=0.5.6
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - urllib3=2.2.3
  - wasabi=1.1.2
  - weasel=0.4.1
  - webencodings=0.5.1
  - wheel=0.45.1
  - wordcloud=1.9.3
  - wrapt=1.16.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.2
  - xyzservices=2025.1.0
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - yarl=1.9.4
  - zipp=3.21.0
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - huggingface-hub==0.23.2
      - mpmath==1.3.0
      - networkx==3.1
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.0
      - sympy==1.13.3
      - torch==2.4.1
      - torchvision==0.19.1
